service:
  name: kratos-base-project.administrator.service
  version: v1
trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/kratos-base-project-administrator?parseTime=true&collation=utf8mb4_unicode_ci&loc=Asia%2FShanghai&charset=utf8mb4
  redis:
    addr: 127.0.0.1:6379
    password:
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  service_key: "administrator-service-key"
  api_key: "administrator-api-key"
consul:
  address: 127.0.0.1:8500
  scheme: http
